version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:12.14.1
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - yarn-v1.0-{{ checksum "yarn.lock" }}
                      - yarn-v1.0-
            - run: yarn --frozen-lockfile
            - save_cache:
                  paths:
                      - ~/.cache/yarn
                  key: yarn-v1.0-{{ checksum "yarn.lock" }}
            - run: yarn build
            - store_artifacts:
                  path: ./build
            - run: yarn moxci build/index.html
